export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const USER_LOGIN_BEGIN = 'USER_LOGIN_BEGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_BEGIN = 'USER_REGISTER_BEGIN';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const GET_SECTION = 'GET_SECTION';
export const BEFORE_GET_SECTION = 'BEFORE_GET_SECTION';
export const ERROR_GET_SECTION = 'ERROR_GET_SECTION';

export const GET_SECTION_DETAIL = 'GET_SECTION_DETAIL';


